import {
  Property,
  Renter,
  Payment,
  Invoice,
  OwnerDashboardStats,
  MaintenanceRequest,
} from "@/types/owner";

// Mock Properties
export const mockProperties: Property[] = [
  {
    id: "p1",
    name: "Apartamento Parque 93",
    address: "Calle 93 #15-20, Apt 801",
    city: "Bogotá",
    type: "apartment",
    status: "occupied",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    rentAmount: 3200000,
    description: "Hermoso apartamento con vista al parque, completamente amoblado",
    amenities: ["Parqueadero", "Gimnasio", "Piscina", "Seguridad 24/7", "Zona BBQ"],
    renterId: "r1",
    createdAt: new Date("2024-01-15"),
    lastUpdated: new Date("2025-11-05"),
  },
  {
    id: "p2",
    name: "Casa Campestre Chía",
    address: "Vereda Fusca, Conjunto Campestre",
    city: "Chía",
    type: "house",
    status: "occupied",
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    rentAmount: 4500000,
    description: "Casa campestre con jardín amplio y chimenea",
    amenities: ["Jardín", "Chimenea", "Garaje 2 carros", "Zona de lavandería", "Estudio"],
    renterId: "r2",
    createdAt: new Date("2024-02-10"),
    lastUpdated: new Date("2025-11-03"),
  },
  {
    id: "p3",
    name: "Estudio Chapinero Alto",
    address: "Carrera 7 #65-30, Apt 402",
    city: "Bogotá",
    type: "studio",
    status: "occupied",
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    rentAmount: 1800000,
    description: "Estudio moderno cerca a universidades y transporte",
    amenities: ["Internet fibra óptica", "Portería", "Zona de coworking"],
    renterId: "r3",
    createdAt: new Date("2024-03-20"),
    lastUpdated: new Date("2025-11-04"),
  },
  {
    id: "p4",
    name: "Apartamento Zona Rosa",
    address: "Calle 82 #12-45, Apt 1502",
    city: "Bogotá",
    type: "apartment",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    area: 90,
    rentAmount: 2800000,
    description: "Apartamento en el corazón de la Zona Rosa",
    amenities: ["Balcón", "Parqueadero", "Cuarto útil", "Gimnasio"],
    availableFrom: new Date("2025-12-01"),
    createdAt: new Date("2024-04-05"),
    lastUpdated: new Date("2025-11-01"),
  },
  {
    id: "p5",
    name: "Penthouse El Poblado",
    address: "Carrera 43A #10-50, PH 2001",
    city: "Medellín",
    type: "penthouse",
    status: "occupied",
    bedrooms: 3,
    bathrooms: 3,
    area: 180,
    rentAmount: 5500000,
    description: "Penthouse de lujo con terraza privada y jacuzzi",
    amenities: ["Terraza", "Jacuzzi", "Parqueadero 2 carros", "Depósito", "Vista panorámica"],
    renterId: "r4",
    createdAt: new Date("2024-05-15"),
    lastUpdated: new Date("2025-11-05"),
  },
  {
    id: "p6",
    name: "Casa Norte Bogotá",
    address: "Calle 127 #52-18",
    city: "Bogotá",
    type: "house",
    status: "maintenance",
    bedrooms: 4,
    bathrooms: 3,
    area: 220,
    rentAmount: 4200000,
    description: "Casa familiar con jardín y patio trasero",
    amenities: ["Jardín frontal", "Patio trasero", "Garaje 3 carros", "Cuarto servicio"],
    createdAt: new Date("2024-06-20"),
    lastUpdated: new Date("2025-11-02"),
  },
  {
    id: "p7",
    name: "Oficina Chicó",
    address: "Carrera 15 #96-32, Of 301",
    city: "Bogotá",
    type: "office",
    status: "occupied",
    bedrooms: 0,
    bathrooms: 2,
    area: 85,
    rentAmount: 3500000,
    description: "Oficina completamente dotada en zona empresarial",
    amenities: ["Sala de juntas", "Cocina", "Recepción", "Internet dedicado", "Aire acondicionado"],
    renterId: "r5",
    createdAt: new Date("2024-07-10"),
    lastUpdated: new Date("2025-11-04"),
  },
  {
    id: "p8",
    name: "Apartamento Laureles",
    address: "Circular 73 #45-28, Apt 603",
    city: "Medellín",
    type: "apartment",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    area: 75,
    rentAmount: 2200000,
    description: "Apartamento acogedor en tradicional barrio de Laureles",
    amenities: ["Balcón", "Parqueadero", "Zona social"],
    availableFrom: new Date("2025-11-15"),
    createdAt: new Date("2024-08-05"),
    lastUpdated: new Date("2025-10-28"),
  },
];

// Mock Renters
export const mockRenters: Renter[] = [
  {
    id: "r1",
    name: "Ana María Jiménez",
    email: "ana.jimenez@gmail.com",
    phone: "+57 310 555 1234",
    avatar: "AJ",
    propertyId: "p1",
    propertyName: "Apartamento Parque 93",
    rentAmount: 3200000,
    paymentStatus: "paid",
    nextPaymentDate: new Date("2025-12-05"),
    contractStart: new Date("2024-06-01"),
    contractEnd: new Date("2025-12-01"),
    documentId: "CC 52123456",
    emergencyContact: {
      name: "Carlos Jiménez",
      phone: "+57 311 555 9876",
      relationship: "Padre",
    },
    depositAmount: 3200000,
    depositPaid: true,
    notes: "Excelente inquilina, siempre paga puntual",
  },
  {
    id: "r2",
    name: "Roberto Sánchez",
    email: "roberto.sanchez@outlook.com",
    phone: "+57 312 555 2345",
    avatar: "RS",
    propertyId: "p2",
    propertyName: "Casa Campestre Chía",
    rentAmount: 4500000,
    paymentStatus: "pending",
    nextPaymentDate: new Date("2025-11-10"),
    contractStart: new Date("2024-08-01"),
    contractEnd: new Date("2026-08-01"),
    documentId: "CC 79456123",
    emergencyContact: {
      name: "María Sánchez",
      phone: "+57 313 555 5432",
      relationship: "Esposa",
    },
    depositAmount: 4500000,
    depositPaid: true,
  },
  {
    id: "r3",
    name: "Laura Martínez",
    email: "laura.martinez@hotmail.com",
    phone: "+57 314 555 3456",
    avatar: "LM",
    propertyId: "p3",
    propertyName: "Estudio Chapinero Alto",
    rentAmount: 1800000,
    paymentStatus: "paid",
    nextPaymentDate: new Date("2025-11-20"),
    contractStart: new Date("2024-09-15"),
    contractEnd: new Date("2025-09-15"),
    documentId: "CC 1015432167",
    depositAmount: 1800000,
    depositPaid: true,
  },
  {
    id: "r4",
    name: "David Ospina",
    email: "david.ospina@gmail.com",
    phone: "+57 315 555 4567",
    avatar: "DO",
    propertyId: "p5",
    propertyName: "Penthouse El Poblado",
    rentAmount: 5500000,
    paymentStatus: "overdue",
    nextPaymentDate: new Date("2025-11-01"),
    contractStart: new Date("2024-10-01"),
    contractEnd: new Date("2026-10-01"),
    documentId: "CC 43789123",
    emergencyContact: {
      name: "Patricia Ospina",
      phone: "+57 316 555 7890",
      relationship: "Hermana",
    },
    depositAmount: 5500000,
    depositPaid: true,
    notes: "Pago atrasado por 5 días, contactado el 04/11",
  },
  {
    id: "r5",
    name: "Empresa TechSolutions SAS",
    email: "admin@techsolutions.co",
    phone: "+57 317 555 5678",
    avatar: "TS",
    propertyId: "p7",
    propertyName: "Oficina Chicó",
    rentAmount: 3500000,
    paymentStatus: "paid",
    nextPaymentDate: new Date("2025-12-01"),
    contractStart: new Date("2024-11-01"),
    contractEnd: new Date("2026-11-01"),
    documentId: "NIT 900123456-1",
    depositAmount: 7000000,
    depositPaid: true,
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: "pay1",
    renterId: "r1",
    renterName: "Ana María Jiménez",
    propertyId: "p1",
    propertyName: "Apartamento Parque 93",
    amount: 3200000,
    dueDate: new Date("2025-11-05"),
    paidDate: new Date("2025-11-03"),
    status: "paid",
    paymentMethod: "Transferencia Bancolombia",
    transactionId: "TRX-2025110301234",
  },
  {
    id: "pay2",
    renterId: "r2",
    renterName: "Roberto Sánchez",
    propertyId: "p2",
    propertyName: "Casa Campestre Chía",
    amount: 4500000,
    dueDate: new Date("2025-11-10"),
    status: "pending",
  },
  {
    id: "pay3",
    renterId: "r3",
    renterName: "Laura Martínez",
    propertyId: "p3",
    propertyName: "Estudio Chapinero Alto",
    amount: 1800000,
    dueDate: new Date("2025-11-20"),
    paidDate: new Date("2025-11-18"),
    status: "paid",
    paymentMethod: "Nequi",
    transactionId: "NEQ-456789123",
  },
  {
    id: "pay4",
    renterId: "r4",
    renterName: "David Ospina",
    propertyId: "p5",
    propertyName: "Penthouse El Poblado",
    amount: 5500000,
    dueDate: new Date("2025-11-01"),
    status: "overdue",
    lateFee: 275000,
    notes: "5 días de retraso",
  },
  {
    id: "pay5",
    renterId: "r5",
    renterName: "Empresa TechSolutions SAS",
    propertyId: "p7",
    propertyName: "Oficina Chicó",
    amount: 3500000,
    dueDate: new Date("2025-12-01"),
    status: "pending",
  },
  // Previous month payments
  {
    id: "pay6",
    renterId: "r1",
    renterName: "Ana María Jiménez",
    propertyId: "p1",
    propertyName: "Apartamento Parque 93",
    amount: 3200000,
    dueDate: new Date("2025-10-05"),
    paidDate: new Date("2025-10-04"),
    status: "paid",
    paymentMethod: "Transferencia Bancolombia",
    transactionId: "TRX-2025100401234",
  },
  {
    id: "pay7",
    renterId: "r2",
    renterName: "Roberto Sánchez",
    propertyId: "p2",
    propertyName: "Casa Campestre Chía",
    amount: 4500000,
    dueDate: new Date("2025-10-10"),
    paidDate: new Date("2025-10-09"),
    status: "paid",
    paymentMethod: "PSE Davivienda",
    transactionId: "PSE-789456123",
  },
];

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2025-001",
    renterId: "r1",
    renterName: "Ana María Jiménez",
    propertyId: "p1",
    propertyName: "Apartamento Parque 93",
    amount: 3200000,
    issueDate: new Date("2025-10-25"),
    dueDate: new Date("2025-11-05"),
    paidDate: new Date("2025-11-03"),
    status: "paid",
    items: [
      { description: "Arriendo mensual - Noviembre 2025", amount: 3200000 },
    ],
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2025-002",
    renterId: "r2",
    renterName: "Roberto Sánchez",
    propertyId: "p2",
    propertyName: "Casa Campestre Chía",
    amount: 4500000,
    issueDate: new Date("2025-10-30"),
    dueDate: new Date("2025-11-10"),
    status: "sent",
    items: [
      { description: "Arriendo mensual - Noviembre 2025", amount: 4500000 },
    ],
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2025-003",
    renterId: "r4",
    renterName: "David Ospina",
    propertyId: "p5",
    propertyName: "Penthouse El Poblado",
    amount: 5775000,
    issueDate: new Date("2025-10-20"),
    dueDate: new Date("2025-11-01"),
    status: "overdue",
    items: [
      { description: "Arriendo mensual - Noviembre 2025", amount: 5500000 },
      { description: "Mora por pago tardío (5%)", amount: 275000 },
    ],
    notes: "Incluye mora por pago tardío",
  },
];

// Dashboard Statistics
export const ownerDashboardStats: OwnerDashboardStats = {
  totalProperties: 8,
  occupiedProperties: 5,
  availableProperties: 2,
  totalRenters: 5,
  monthlyRevenue: 20500000,
  pendingPayments: 2,
  overduePayments: 1,
  occupancyRate: 62.5,
  revenueGrowth: 8.5,
};

// Revenue Chart Data
export const ownerRevenueData = [
  { month: "Ene", revenue: 15200000, occupancy: 50 },
  { month: "Feb", revenue: 16800000, occupancy: 55 },
  { month: "Mar", revenue: 17500000, occupancy: 60 },
  { month: "Abr", revenue: 18200000, occupancy: 60 },
  { month: "May", revenue: 18900000, occupancy: 62.5 },
  { month: "Jun", revenue: 19100000, occupancy: 62.5 },
  { month: "Jul", revenue: 19500000, occupancy: 62.5 },
  { month: "Ago", revenue: 19800000, occupancy: 62.5 },
  { month: "Sep", revenue: 20000000, occupancy: 62.5 },
  { month: "Oct", revenue: 20200000, occupancy: 62.5 },
  { month: "Nov", revenue: 20500000, occupancy: 62.5 },
];

// Maintenance Requests
export const mockMaintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint1",
    propertyId: "p1",
    propertyName: "Apartamento Parque 93",
    renterId: "r1",
    renterName: "Ana María Jiménez",
    title: "Fuga de agua en baño principal",
    description: "Se presenta goteo constante en la llave del lavamanos",
    priority: "high",
    status: "in-progress",
    createdAt: new Date("2025-11-03"),
    cost: 150000,
  },
  {
    id: "maint2",
    propertyId: "p2",
    propertyName: "Casa Campestre Chía",
    renterId: "r2",
    renterName: "Roberto Sánchez",
    title: "Calentador no funciona",
    description: "El calentador de agua dejó de funcionar desde ayer",
    priority: "urgent",
    status: "open",
    createdAt: new Date("2025-11-05"),
  },
  {
    id: "maint3",
    propertyId: "p5",
    propertyName: "Penthouse El Poblado",
    renterId: "r4",
    renterName: "David Ospina",
    title: "Bombillo de cocina fundido",
    description: "Necesita reemplazo del bombillo principal de la cocina",
    priority: "low",
    status: "resolved",
    createdAt: new Date("2025-10-28"),
    resolvedAt: new Date("2025-10-30"),
    cost: 25000,
  },
];

// Recent Activity
export const ownerRecentActivity = [
  {
    id: "act1",
    type: "payment",
    title: "Pago recibido",
    description: "Ana María Jiménez pagó $3.2M",
    timestamp: new Date("2025-11-03T10:30:00"),
    amount: 3200000,
  },
  {
    id: "act2",
    type: "maintenance",
    title: "Nueva solicitud de mantenimiento",
    description: "Roberto Sánchez reportó: Calentador no funciona",
    timestamp: new Date("2025-11-05T08:15:00"),
  },
  {
    id: "act3",
    type: "inquiry",
    title: "Nueva consulta",
    description: "Persona interesada en Apartamento Zona Rosa",
    timestamp: new Date("2025-11-04T16:45:00"),
  },
  {
    id: "act4",
    type: "contract",
    title: "Contrato próximo a vencer",
    description: "Contrato de Laura Martínez vence en 10 meses",
    timestamp: new Date("2025-11-04T09:00:00"),
  },
  {
    id: "act5",
    type: "payment",
    title: "Pago pendiente",
    description: "David Ospina - Pago vencido hace 5 días",
    timestamp: new Date("2025-11-01T00:00:00"),
  },
];
